// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check overall API health with integration statuses",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/hello": {
            "get": {
                "description": "Guaranteed liveness probe - always available regardless of integration status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Hello endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HelloResponse"
                        }
                    }
                }
            }
        },
        "/integrations/status": {
            "get": {
                "description": "Get operational status of all database integrations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "integrations"
                ],
                "summary": "Integration status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.IntegrationsStatusResponse"
                        }
                    }
                }
            }
        },
        "/mongo/documents": {
            "get": {
                "description": "Get all documents from MongoDB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mongo"
                ],
                "summary": "Get all MongoDB documents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/mongo.Document"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new document in MongoDB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mongo"
                ],
                "summary": "Create MongoDB document",
                "parameters": [
                    {
                        "description": "Document data",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mongo.DocumentInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/mongo.Document"
                        }
                    }
                }
            }
        },
        "/mongo/documents/{id}": {
            "get": {
                "description": "Get a document from MongoDB by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mongo"
                ],
                "summary": "Get MongoDB document by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mongo.Document"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a document in MongoDB by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mongo"
                ],
                "summary": "Update MongoDB document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Document data",
                        "name": "document",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/mongo.DocumentInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/mongo.Document"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a document from MongoDB by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mongo"
                ],
                "summary": "Delete MongoDB document",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Document ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/mongo/health": {
            "get": {
                "description": "Check MongoDB connection status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mongo"
                ],
                "summary": "MongoDB health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/postgres/health": {
            "get": {
                "description": "Check PostgreSQL connection status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postgres"
                ],
                "summary": "PostgreSQL health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/postgres/records": {
            "get": {
                "description": "Get all records from PostgreSQL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postgres"
                ],
                "summary": "Get all PostgreSQL records",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/postgres.Record"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new record in PostgreSQL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postgres"
                ],
                "summary": "Create PostgreSQL record",
                "parameters": [
                    {
                        "description": "Record data",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/postgres.RecordInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/postgres.Record"
                        }
                    }
                }
            }
        },
        "/postgres/records/{id}": {
            "get": {
                "description": "Get a record from PostgreSQL by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postgres"
                ],
                "summary": "Get PostgreSQL record by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/postgres.Record"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a record in PostgreSQL by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postgres"
                ],
                "summary": "Update PostgreSQL record",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Record data",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/postgres.RecordInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/postgres.Record"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a record from PostgreSQL by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "postgres"
                ],
                "summary": "Delete PostgreSQL record",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Record ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/redis/cache": {
            "post": {
                "description": "Set a key-value pair in Redis cache",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "redis"
                ],
                "summary": "Set Redis cache item",
                "parameters": [
                    {
                        "description": "Cache item data",
                        "name": "item",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/redis.CacheItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/redis/cache/{key}": {
            "get": {
                "description": "Get a value from Redis cache by key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "redis"
                ],
                "summary": "Get Redis cache item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/redis.CacheItem"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a key from Redis cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "redis"
                ],
                "summary": "Delete Redis cache item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cache key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/redis/health": {
            "get": {
                "description": "Check Redis connection status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "redis"
                ],
                "summary": "Redis health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.HelloResponse": {
            "type": "object",
            "properties": {
                "integrations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.IntegrationStatus": {
            "type": "object",
            "properties": {
                "enabled": {
                    "description": "Whether integration is operational",
                    "type": "boolean"
                },
                "error": {
                    "description": "Failure reason if disabled",
                    "type": "string"
                },
                "lastCheckTime": {
                    "description": "When status was last updated",
                    "type": "string"
                },
                "migrationStatus": {
                    "description": "Schema migration status",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.MigrationStatus"
                        }
                    ]
                },
                "name": {
                    "description": "Integration identifier (\"postgres\", \"redis\", \"mongo\")",
                    "type": "string"
                }
            }
        },
        "models.IntegrationsStatusResponse": {
            "type": "object",
            "properties": {
                "integrations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.IntegrationStatus"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/models.StatusSummary"
                }
            }
        },
        "models.MigrationStatus": {
            "type": "string",
            "enum": [
                "migrated",
                "failed",
                "not_configured"
            ],
            "x-enum-varnames": [
                "MigrationStatusMigrated",
                "MigrationStatusFailed",
                "MigrationStatusNotConfigured"
            ]
        },
        "models.StatusSummary": {
            "type": "object",
            "properties": {
                "disabled": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "mongo.Document": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "mongo.DocumentInput": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "postgres.Record": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "postgres.RecordInput": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string"
                }
            }
        },
        "redis.CacheItem": {
            "type": "object",
            "properties": {
                "data": {},
                "expires_in": {
                    "description": "seconds",
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Simple Go API",
	Description:      "A simple Go API with optional PostgreSQL, Redis, and MongoDB integrations",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
